Some hours later, you come home after a tough dealing with a customer.
{i}Why do I have to work until this hour?{/i}
{i}I really have to change my job!{/i}
Emily?
Why are you naked like this, Emily?
I... hic... want to... hic... have a moon-tanned skin... hic...
{i}She's drunk.{/i}
Where did you drink, Emily?
Who told you that I went out drinking?
Did you hire a detective to follow me, you jerk?
You're drunk.
Let's go to sleep, Emily.
Does the detective tell you that I'm too horny now, eh, bad boy?
{i}She's drunk now.{/i}
{i}But I'm too horny also.{/i}
{i}She's been here with Suzie for a whole week and I couldn't even masturbate!{/i}
{i}Should I have fun with her now?{/i}
I'm going in now, Emily.
Hic...
Oh...
Oh...
So good... Hic...
You're so tight tonight, Emily.
Really? Hic...
I thought your cock is bigger than usual tonight... hic...
Oh... oh...
{i}Yeah. Maybe because Suzie's also here...{/i}
Oh... fuck me faster... [povname]... oh...
Oh... oh...
Faster... faster...
Not so loud, Emily.
You might wake Suzie up.
I don't care... faster... hic...
If she's awake now, we'll fuck her... oh... oh...
Really?
Yeah... I'll make her suck my pussy when you're fucking her like crazy... hic... oh...
{i}Shit! Imagining what she says is too much for me...{/i}
I'm gonna come now, Emily...
Give it to me... oh... oh...
Oh...
Ugh...
{i}Did she really think I would suck... that thing of her?{/i}
{i}So gross!{/i}
Some hours later.
Ah... My head is spinning around...
Some minutes later.
Hm?
{i}She smells like alcohol.{/i}
{i}She's drunk!{/i}
{i}I can't let her sleep like this.{/i}
{i}But changing her clothes is...{/i}
{i}Well, what should I do now?{/i}
{i}I'll help her change into her pajama.{/i}
Some minutes later.
Um...
{i}Shit, I thought I would only change her clothes.{/i}
{i}Where is this place?{/i}
{i}But I couldn't stop myself from touching her!{/i}
{i}Why do I feel tickled down there?{/i}
[povname]?
Oh...
{i}He's sucking my vagina...{/i}
{i}It's... dirty!{/i}
{i}But what is this feeling?{/i}
Um...
[povname]... be patient...
We'll continue this on our wedding night...
{i}But I'm too horny now!{/i}
{i}She doesn't stop me either!{/i}
{i}Should I keep going or stop here?{/i}
Don't worry, Suzie.
I'll be gentle.
Er?
I'm going in now.
Er?
Ah... I'm hurt... [povname]!
Don't worry. It'll be over soon.
Ugh... so tight...
Ah...
I took your virgin, Suzie... Ugh...
Ah... Gentle, please...
Ah...
Do you feel good, Suzie?
No... it's just... I'm so hurt... Ah...
Don't worry...
Ah...
You'll feel good next time...
Mm... mm...
I love you, Suzie...
Finish it... please...
Ugh... I can't hold it anymore...
Here I come, Suzie...
Ugh...
Oh... oh... I'm coming, Suzie...
Ugh...
Um...
It was our first time so I couldn't hold it longer.
I'll make you feel good next time, Suzie.
{i}I'm still hurt...{/i}
Er?
What are you doing, [povname]?
I love you, Emily!
I know that, but what if people see us?
No one's coming here.
But what if they come?
{i}He positioned himself between my crotch already!{/i}
Hey, [povname]!
Are you listening to what I'm saying?
What if they come?
So what?
Can't a man fuck his girlfriend?
But...
{i}His penis is preparing to enter me!{/i}
[povname], I'm not wet yet!
You will after some minutes, trust me!
{i}I'm too horny to stop now!{/i}
Ouch, [povname]!
{i}My vagina's so dry...{/i}
{i}It's hurt...{/i}
So good, Emily... ah... ah...
Oh... slow down, [povname]...
It's hurt...
My vagina's so dry...
It will be wet soon... oh... oh...
Mm... mm...
Do you love me, [povname]?
I love you, Emily...
Then don't do this again, okay?
Okay, Emily... oh...
Mm... mm...
{i}I'm starting to get wet down there...{/i}
See, Emily?
I knew you would get wet soon.
Mm... mm...
I'm going faster now!
Oh... oh...
So good... [povname]...
Do you love me, Emily?
Love... love... mm... mm...
I love... mm... mm... you... mm... mm...
Love me more... [povname]... love me more... mm... mm...
I'm coming... Emily...
Faster... faster...
Make me come too... mm... mm...
Oh... I'm coming now... oh...
A little bit more... honey... oh...
Fuck me just a little bit more... oh...
Oh...
Ugh...
{i}I didn't come yet...{/i}
{i}If he had waited for a little bit more...{/i}
{i}Oh my gosh!{/i}
{i}It's... hard again!{/i}
Oh... oh...
You're not tired, [povname]?
I want to make you come too, Emily.
Mm... I love you, [povname]...
I love you, too, Emily.
Mm... mm...
Good... mm...
Faster... faster...
Make me come, [povname]... oh... oh...
Hey, [povname], let me on top of you...
You want to come that much, Emily?
No, it's just that... I'm worried that you'll be too tired to continue...
Oh... okay, Emily.
{i}I know she's just embarrassed to say that she wants to come so badly.{/i}
Oh... oh...
{i}Every time I want to come, I always climb on top of [povname].{/i}
{i}Somehow I could come easily this way.
Oh... oh...
You're so good, Emily!
Oh... oh...
I'm coming, Emily!
I'm gonna come too...
Oh... oh...
Ugh...
Mm... mm...
{i}Looking at her like this, I'm horny somehow.{/i}
{i}Should I have some fun with her?{/i}
{i}Why not?{/i}
{i}Remove her trousers, done.{/i}
{i}Remove her panty, done.{/i}
Er, what are you doing?
I'm doing a boyfriend's job, Emily.
I'm going in now.
Wait.
Oh... oh...
Do you feel good, honey?
Um... um...
{i}She doesn't answer.{/i}
{i}What's she thinking?{/i}
{i}Is she thinking that Alex must be the one fucking her now?{/i}
{i}Fuck!{/i}
Ah... ah...
Do you feel good, honey?
{i}Still silent, eh?{/i}
{i}I'll make you scream this time.{/i}
Ah.. ah... slow down, [povname]!
Do you feel good?
I said slow down!
No, I can't.
Oh.. oh...
You're so tight.
Can I come inside?
Go on, just finish.
Ah... ah...
Ohhhh....
Ah.....
That was pretty good.
Do you feel good, too, honey?
Just go home, please.
Er?
Go home!
Ok, see you tomorrow.
{i}Hmm... She's not here?{/i}
{i}Maybe she's on the bed already.{/i}
{i}That's right.{/i}
{i}The annoyed princess is on the bed already.{/i}
{i}This view makes me too horny.{/i}
{i}I want to penetrate her immediately.{/i}
{i}But knowing her, she'll never let me do that without a foreplay.{/i}
What took you so long, babe?
It's only 15 minutes, babe.
It's not appropriate to let a girl wait for you even 1 minute, [povname].
{i}But if I don't have a shower, you won't let me come near you.{/i}
I'm sorry, babe.
As you're climbing on top of her from behind, Emily says:
No, lie next to me, babe.
Ok, honey.
You smell really good, honey.
Are you sure?
What do you mean?
I'm wondering how many girls' scents you smelled already.
I only have you, babe!
I can't trust men.
Again, honey?
I know your father wasn't a good man.
But I'm not like him.
I'm not sure.
My mom was so naive to trust him.
And I'm thinking I'm so naive sometimes, too.
Who told you that you were naive?
That guy had to be stupid.
What did you say?
{i}Shit, I spoke it out loud!{/i}
{i}If this continues, she'll leave me sleeping alone again.{/i}
{i}It's not the time to be gentle anymore.{/i}
What are you doing?
I'm doing what a man should do to his girlfriend.
Umm...
{i}Her lips are so sweet tonight.{/i}
After some minutes...
You're weird tonight, [povname]!
No, I'm not.
I'm just loving you more than before.
Let's get the towel out of the way.
Out of the way for what?
For this...
While you're sucking her right nipple, your right hand starts to squeeze her left breast.
Oh... Easy...
Umm... Don't bite me...
As she starts to breathe heavily...
Your little girl is as cute as always.
Don't say that, I'm embarrassed.
Move apart your thighs, Emily.
No, I won't...
Hey, I told you that I wouldn't...
It's ok, I'll spread your legs for you.
No!
Ah...
{i}I knew it!{/i}
{i}Just sucking her pussy and she'll stop complaining.
Umm... [povname]...
Are you ready, Emily?
Um...
{i}Don't answer is her way of saying she's ready.{/i}
{i}Are you ready, my boy?{/i}
Ah...
I'm going in now.
Aahhh...
Wow, you're so tight tonight.
I guess your girl is missing me, eh?
Don't say that!
Alright.
{i}I guess more than a week without doing it makes it tighter than usual.{/i}
With a hard push...
Ouch...
I'm moving now, babe.
Don't tell me that...
Huff... huff...
You're so tight tonight.
I... huff... know...
I've never felt you as tight as this before...
Stop... huff... saying... that...
Do you feel good, honey?
Yes... huff... good... ummm...
Am I the best, huh?
You're... the only... huff... man... I've ever... huff...
You knew that... um...
Stop saying... those... huff... things... um...
I'm so close...
Me, too... ah....
Are you coming?
Yes... yes... I'm coming...
Aahhh....
Are you on the pill?
I don't care, just come... ahh...
I'm coming now, receiving my seeds, honey!
Aahhhh...
Ugh...
I'm still mad that you said who told I was naive was crazy.
{i}What? She still remembers even after this?{/i}
Give me your face, honey!
Ah...
I'm still mad that you said who told I was naive was crazy.
{i}What? She still remembers even after this?{/i}
{i}Is she sleeping already?{/i}
{i}Hmm... I guess I will get closer to have a better look at her?{/i}
{i}Sure, why not?{/i}
{i}She's so cute from this angle.{/i}
{i}I wish I could just...{/i}
What are you doing, [povname]?
Uh... uhm...
Please sleep, [povname]...
{i}Shit, she's so cute.{/i}
{i}I'm too horny now.{/i}
{i}She's not looking at me.{/i}
{i}Maybe she's horny too but she's shy.{/i}
{i}Should I make a move now?{/i}
{i}Yeah, I think that's what she wants now.{/i}
Suddenly, you hold her cheek and your face approaches hers.
Er?
Surprisingly, Suzie accepts your kiss.
You taste her lips and explores the depth of her mouth.
You're lost in passion.
Your tongues intertwine and her breath escalates strongly.
Suddenly, she removes herself from your kiss.
But her heart's racing.
You can feel her heartbeats.
You're overwhelmed by desire.
You think of uncovering her breasts, to see what are inside the pink pajama.
Will you do that?
{i}Why not?{/i}
{i}Her nipple's hard already.{/i}
{i}So cute.{/i}
{i}Why is [povname] doing this?{/i}
{i}Why haven't I stopped him?{/i}
{i}It feels so...{/i}
{i}Does he like what he sees?{/i}
Realizing that she doesn't protest, you want to feel her breast, the first Asian breast in your life.
Will you do that?
{i}She wants me to touch her for sure!{/i}
Without any protests, Suzie gives a soft moan.
Um...
Your breast's so soft.
And beautiful.
No, [povname]. Please stop.
{i}Stop? Stop now?{/i}
{i}She doesn't want more?{/i}
{i}But she still lets me touch her boob.{/i}
{i}Why must I stop?{/i}
Umm...
Seeing that Suzie doesn't say anything, you want to do more.
{i}Her crotch's so inviting, should I feel it?{/i}
{i}I'm too horny, I want to touch her more.{/i}
Oh...
No, [povname].
This is wrong.
Sorry, Suzie.
I can't restrain myself.
It's ok. See you tomorrow.
Sure, sleep well, Suzie.
{i}My heart's still racing.{/i}
{i}I can’t believe I told him it was ok.{/i}
{i}Is it something I want him to do again?{/i}
{i}No, I shouldn't. She might get angry.{/i}
Sorry, Suzie.
Um... I must sleep now.
Yeah. See you tomorrow.
Yeah... see you...
{i}My heart's still racing.{/i}
{i}The fuck?{/i}
{i}No, no, no, no!{/i}
{i}I've been waiting for 4 years!{/i}
Suzie, I know you're tired.
But you know, this is my first night with you, so...
I understand, [povname].
Just please be gentle.
This is my first night and I'm tired.
Yeah, don't worry.
Would you please close your eyes, [povname]?
Uhm, okay.
Are you done, Suzie?
I'm done.
You could open your eyes now.
{i}She's still shy.{/i}
{i}Let's dig in!{/i}
Eh?
Please be gentle, [povname]!
Don't worry, Suzie.
Please be gentle, I'm scared!
Don't worry.
I'll be very gentle!
{i}Let's begin with her nipple.{/i}
{i}She smells so good!{/i}
Mm...
Mm...
Oh...
Oh...
Please remember to be gentle when you go in, [povname]!
Don't worry, Suzie.
No!
Don't look too close!
Eh?
Mm...
No, it's dirty!
Mm...
Oh...
{i}I've never felt like this when I touched myself alone!{/i}
Mm...
Oh...
[povname]...
{i}He stopped...{/i}
Eh?
Wait!
Ah!
It won't fit!
Don't worry.
Please stop!
You'll feel good soon, Suzie.
No!
I don't want it anymore!
Please stop!
Ah!!!
It's fine now, Suzie.
No! You liar!
You said you would be gentle!
You'll feel good soon, Suzie.
Ugh... ugh... ugh...
Are you still hurt, Suzie?
I'm... ugh... still hurt... ugh...
I'll be gentle, don't worry.
You liar... ugh...
You're so tight, Suzie... oh...
I've... never... ugh... done this... before... ugh...
Are you still hurt?
It's better now... mm...
Do you start to feel good?
Mm... mm...
Do you feel good, Suzie?
Mm... don't ask me... mm...
{i}It seems that she starts to feel good.{/i}
Mm... mm...
{i}It's time for me to enjoy now.{/i}
Oh... oh...
Don't... be too rough..., [povname]...
Mm... mm...
Oh... oh...
You liar... oh...
You're... mm... not gentle... ah...
I can't hold it anymore... oh...
Mm... mm...
You're too tight!
I'm coming, Suzie!
Ugh... ugh...
I'm coming...
Oh... oh...
Oh...
Ugh...
Mm...
Lie down with me, please...
Don't ever leave me, [povname]...
I'll never leave you, Suzie.
{i}Suzie's pussy is so inviting.{/i}
{i}But I have to fuck Emily now.{/i}
{i}Shit!{/i}
I'm going in now!
Oh...
Yeah!... oh...
Fuck me... fuck me...
Mm...
Oh... yeah...
Ah... oh...
{i}Shit!{/i}
Mm...
Oh...
{i}[povname] is grunting even though he was angry just some minutes ago.{/i}
{i}I guess he likes her vagina.{/i}
Oh... yeah...
Mm...
{i}He isn't making love with me but her body is caressing me down there.{/i}
Oh... oh...
{i}I'm starting to feel aroused also...{/i}
Mm...
Oh... so good...
Mm...
You're so good at this, [povname]... oh...
Now, faster...
Mm...
Fuck me faster! Oh...
Oh... yeah...
Good... good...
Mm...
Fuck me... fuck me...
Ah... I can't hold it anymore, Emily...
Mm...
Come... come for me... oh...
Shit... I'm coming...
Oh...
Oh...
Oh...
I can feel it, Suzie...
Mm?
I can feel he's coming inside me...
Mm... yeah...
Don't worry, Suzie.
I'll buy a strap-on soon.
I'll be the first one to take you to heaven.
Mm... I don't want to have sex yet, Emily.
{i}Fuck!{/i}
{i}I really can't let it go on like this!{/i}
4 years later.
[povname], do you take Suzie to be your wedded wife, to live together in marriage?
Do you promise to love her, comfort her, honor and keep her for better or worse, for richer or poorer, in sickness and health, and forsaking all others, be faithful only to her, for as long as you both shall live?
I do.
Suzie, do you take [povname] to be your wedded husband to live together in marriage?
Do you promise to love him, comfort him, honor and keep him for better or worse, for richer or poorer, in sickness and health and forsaking all others, be faithful only to him so long as you both shall live?
I do.
Meanwhile, at the other side of the pavillion.
So, why don't you become a witness of their wedding after coming all the way here?
I'm just here to protect you.
That's my job.
No need to hide that.
I know you've been in love with him for a long time.
I don't know what you're talking about.
Okay!
Not fun at all.
I'm swimming now.
Remember to protect me!
'cause that your job, haha...
That night.
Are you tired, Suzie?
Just a little, [povname].
This is our first night as husband and wife, Suzie.
Yeah, [povname].
{i}Yes, this is really the first night.{/i}
{i}She said she wanted to keep her virginity until marriage.{/i}
{i}So I could only kiss, caress her.{/i}
{i}Yup, 4 years already.{/i}
{i}She always says love is patience.{/i}
Let's go to sleep, [povname].
{i}The fuck?{/i}
{i}No, no, no, no!{/i}
{i}I've been waiting for 4 years!{/i}
Suzie, I know you're tired.
But you know, this is my first night with you, so...
I understand, [povname].
Just please be gentle.
This is my first night and I'm tired.
Yeah, don't worry.
Would you please close your eyes, [povname]?
Uhm, okay.
Are you done, Suzie?
I'm done.
You could open your eyes now.
{i}She's still shy.{/i}
{i}Let's dig in!{/i}
Eh?
Please be gentle, [povname]!
Don't worry, Suzie.
Please be gentle, I'm scared!
Don't worry.
I'll be very gentle!
{i}Let's begin with her nipple.{/i}
{i}She smells so good!{/i}
Mm...
Mm...
Oh...
Oh...
Please remember to be gentle when you go in, [povname]!
Don't worry, Suzie.
No!
Don't look too close!
Eh?
Mm...
No, it's dirty!
Mm...
Oh...
{i}I've never felt like this when I touched myself alone!{/i}
Mm...
Oh...
[povname]...
{i}He stopped...{/i}
Eh?
Wait!
Ah!
It won't fit!
Don't worry.
Please stop!
You'll feel good soon, Suzie.
No!
I don't want it anymore!
Please stop!
Ah!!!
It's fine now, Suzie.
No! You liar!
You said you would be gentle!
You'll feel good soon, Suzie.
Ugh... ugh... ugh...
Are you still hurt, Suzie?
I'm... ugh... still hurt... ugh...
I'll be gentle, don't worry.
You liar... ugh...
You're so tight, Suzie... oh...
I've... never... ugh... done this... before... ugh...
Are you still hurt?
It's better now... mm...
Do you start to feel good?
Mm... mm...
Do you feel good, Suzie?
Mm... don't ask me... mm...
{i}It seems that she starts to feel good.{/i}
Mm... mm...
{i}It's time for me to enjoy now.{/i}
Oh... oh...
Don't... be too rough..., [povname]...
Mm... mm...
Oh... oh...
You liar... oh...
You're... mm... not gentle... ah...
I can't hold it anymore... oh...
Mm... mm...
You're too tight!
I'm coming, Suzie!
Ugh... ugh...
I'm coming...
Oh... oh...
Oh...
Ugh...
Mm...
Lie down with me, please...
Don't ever leave me, [povname]...
I'll never leave you, Suzie.
One year later.
What did the doctor say, Suzie?
Everything's fine.
Our baby is healthy.
Do you think of a name for her yet?
I'm not good at choosing.
Yeah, you always say that.
But why do you think our child will be a girl, [povname]?
Well, I don't know.
I just think so.
Ah, so Yue-Yue will start to live with us next week?
Uhm, I need someone to look after me when I'm going to give birth.
Well, I'm not sure about that.
She's too young.
Hey, don't ever think about any pervert stuff with her, okay?
Why should I think about anything with her?
Who knows?
They say men are beasts inside.
Not me, I'm a gentleman.
No, you're a liar.
Again.
You keep calling me liar after our first night.
Ah, Yue-Yue told me that Ah Qing was murdered!
Your ex-fiance in China?
Yeah.
Who killed him?
I don't know.
My father was murdered also.
I didn't want to be a widow like my mother.
That's why I ran away.
You have me now.
Don't worry, Suzie.
Yeah.
I have you now.
When you start a new week.
{i}An information about changing staff?{/i}
{i}What?{/i}
{i}Suzie resigned and went back to China?{/i}
Some months later, in Wuxi, Jiangsu, China.
(From now on, Suzie and her fiance speak in Mandarin only.)
Please go outside!
I have to sleep!
And I have to fuck!
But we haven't got married yet!
Can't you just wait for another week?
Why?
We're engaged!
I know, but...
At least give me a handjob!
Handjob?
You mean I use my hand to...
Of course, is there another type of handjob?
Uhm...
Please go outside after I finish it.
Can't I just sleep here with you?
I want to be alone until I'm your wife.
Hmm... Okay.
{i}This is the thing will take my virginity.{/i}
What are you waiting for?
Start using your hand!
{i}What the fuck is this?{/i}
{i}I'm not sure if this is the right way to do it.{/i}
{i}What is she doing?{/i}
{i}I'm not experienced in these things.{/i}
{i}I can't feel a damn thing!{/i}
{i}I hope he'll finish it soon.{/i}
{i}She's not good at all!{/i}
{i}I'm sleepy.{/i}
Hey, do you know how to do it?
Er, what do you mean?
Do you know how to give a handjob?
I'm not experienced in this.
How can I come like this?
I'm even better than you!
If I did it myself, I had come already!
How about you go outside and do it yourself?
I think that'll be better for both of us.
What?
Eh?
Are you mocking me?
No, I'm not mocking you!
You're my wife!
You have to please me not to mock me!
I'm sorry but I didn't mean to mock you!
Hey! No!
I don't want it!
Silent!
No...
Sooner or later, you'll have to give it to me!
I know, but...
Ah!
Oh... so tight...
Mmm... mm... mm...
I've never fucked a pussy as tight as yours... oh...
Don't... mmm... say that to me... mmm...
Why? You're my woman!
Even so... I want you to respect... mmm... me...
What the fuck?
Mmm...
You only have one job to do: spread your legs!
Mmm...
Why the fuck should I have to respect you?
Mmm... half of the new corporation is mine... mmm...
Don't forget... that... mmm...
Shit!
So what?
Ah...
Do you want to betray me?
No... mmm...
Slow down... mmm...
Why?
I'm hurt...
I don't care!
Mmm...
Don't forget that we know where Yue-Yue is!
No! Don't touch her!
Then don't betray me!
Ah... Ah...
Shit... I'm coming... Oh...
Outside, please...
The fuck?
I'm your husband!
Oh...
I don't wanna get pregnant... mmm... yet...
Ah...
Mmm...
I'll fuck you again after some minutes. Hahaha...
You're not a virgin?
What the fuck?
Who fucked you before me?
Answer me!
Hey, are you deaf?
Fuck!
15 minutes later.
Someone else fucked me before you.
So what?
What the fuck with your attitude?
You have the right to fuck anyone you want before our wedding, but I don't?
What the fuck?
I'm a man!
And?
If you don't want to be cuckolded, behave yourself.
What? Fuck you!
When you start a new week.
{i}An information about changing staff?{/i}
{i}What?{/i}
{i}Suzie resigned and went back to China?{/i}
Some months later, in Wuxi, Jiangsu, China.
(From now on, Suzie and her fiance speak in Mandarin only.)
Please go outside!
I have to sleep!
And I have to fuck!
But we haven't got married yet!
Can't you just wait for another week?
Why?
We're engaged!
I know, but...
At least give me a handjob!
Handjob?
You mean I use my hand to...
Of course, is there another type of handjob?
Uhm...
Please go outside after I finish it.
Can't I just sleep here with you?
I want to be alone until I'm your wife.
Hmm... Okay.
{i}This is the thing will take my virginity.{/i}
What are you waiting for?
Start using your hand!
{i}What the fuck is this?{/i}
{i}I'm not sure if this is the right way to do it.{/i}
{i}What is she doing?{/i}
{i}I'm not experienced in these things.{/i}
{i}I can't feel a damn thing!{/i}
{i}I hope he'll finish it soon.{/i}
{i}She's not good at all!{/i}
{i}I'm sleepy.{/i}
Hey, do you know how to do it?
Er, what do you mean?
Do you know how to give a handjob?
I'm not experienced in this.
How can I come like this?
I'm even better than you!
If I did it myself, I had come already!
How about you go outside and do it yourself?
I think that'll be better for both of us.
What?
Eh?
Are you mocking me?
No, I'm not mocking you!
You're my wife!
You have to please me not to mock me!
I'm sorry but I didn't mean to mock you!
Hey! No!
I don't want it!
Silent!
No...
Sooner or later, you'll have to give it to me!
I know, but...
Ah!
Oh... so tight...
Mmm... mm... mm...
I've never fucked a pussy as tight as yours... oh...
Don't... mmm... say that to me... mmm...
Why? You're my woman!
Even so... I want you to respect... mmm... me...
What the fuck?
Mmm...
You only have one job to do: spread your legs!
Mmm...
Why the fuck should I have to respect you?
Mmm... half of the new corporation is mine... mmm...
Don't forget... that... mmm...
Shit!
So what?
Ah...
Do you want to betray me?
No... mmm...
Slow down... mmm...
Why?
I'm hurt...
I don't care!
Mmm...
Don't forget that we know where Yue-Yue is!
No! Don't touch her!
Then don't betray me!
Ah... Ah...
Shit... I'm coming... Oh...
Outside, please...
The fuck?
I'm your husband!
Oh...
I don't wanna get pregnant... mmm... yet...
Ah...
Mmm...
I'll fuck you again after some minutes. Hahaha...
You're my woman now, Qiu-Shui.
Hey, get up and clean yourself before I continue to fuck you again!
Just once is not enough for me!
Hey, are you deaf?
Fuck!
{i}They're fucking for sure!{/i}
{i}Fuck!{/i}
{i}I can't hear clearly.{/i}
{i}But she's having a good fuck for sure!{/i}
{i}Fuck!{/i}
Huff... huff...
{i}His thing is bigger than [povname]'s.{/i}
Oh... ah...
{i}It's stretching me inside...{/i}
{i}He's going faster now!{/i}
{i}Don't tell me he's going to come inside her!{/i}
{i}Shit. He did it.{/i}
{i}Why did she let him do that?{/i}
{i}Why?{/i}
Ah...
{i}I feel it, he's exploding inside me...{/i}
Oh...
This is the best day of my life, Emily!
Umm...
{i}But what about them?{/i}
Ooh.
Look who's horny already.
Are you ready, dear?
You guys are so obscene.
I'm out of here.
I'll never join you guys again!
{i}Part one of the plan was a success.{/i}
{i}Now part two.{/i}
{i}What the fuck is he standing behind Emily for?{/i}
Do you feel good, [povname]?
Er?
Hey!
Let me give you a memorable night.
Hey, wait.
I'm not ready!
But I'm ready.
{i}What the fuck?{/i}
Ohhh.....
Hey, Woody!
That's not a part of the deal!
{i}Fuck my life!{/i}
Oh... oh... oh...
What's the deal?
I've never signed anything with you.
{i}His cock is so long and thick.{/i}
{i}It's stretching my pussy...{/i}
Um... um... um...
Woody George keeps on having his way with Emily.
Who is being humiliated here?
[povname], who is looking at his ex-girlfriend moaning with a dick not his?
Or is it Alex? Who thought he could have a chance with Emily but he lost not only Suzie but also Emily?
Do you want me to come inside?
Huff... no... huff... please don't... huff...
Not this time then.
There's someone waiting for you here. Haha.
You think I'll touch her again?
Forget about that!
Fuck you, Woody!
Oh...
Who said that I would let you touch any girl under my watch, [povname]?
What?
You can have her, Alex.
But for this time only.
She's not yours, asshole!
Oh, really?
Not only Emily, Suzie'll soon be mine.
I'll never let that happen!
We'll see.
Ohhh...
Oh, there he comes.
You think so?
Yes, I think so.
You should get it back before he uploads it.
Hm... If you say so...
Suzie gets back to her desk, still thinking if she should go or not.
{i}[povname] didn't give me an advice.{/i}
{i}Should I really come to his place?{/i}
{i}I know I can only get it back if I let him... me again.{/i}
{i}What will happen if Alex finds out?{/i}
{i}He knew that I was still a virgin when I started to date him.{/i}
{i}Oh, wait a minute.{/i}
{i}Alex was a jerk last night too.{/i}
{i}I don't want to date him anymore.{/i}
{i}Once or twice, it won't change the fact that I'm not a virgin anymore...{/i}
After work, at Jim Brie's hotel room.
I knew you would come.
Come in, please.
Sit down, please.
Do you want to have a drink?
No, thanks.
I don't wanna bother you.
Please give me the USB drive and I'll go immediately.
But first you must help me with something.
What do you want me to do?
This.
He's saying while he's unzipping his pants.
Before Suzie's eyes is the thing that defiled her not long ago.
What?
Just start jerking it.
{i}I knew it would come to this.{/i}
{i}But I think it's better with just my hand like this.{/i}
Is this okay?
Yes, just like that.
Your hand is so soft.
You were still a virgin back then, right?
I'm pretty sure your boyfriend is lucky.
He must let you massage his cock like this everyday for sure. Haha.
No! I've never done this before!
What? I'm the first man again?
Shit! What you just said is too much!
That's it! Keep going!
I'm gonna come soon!
I'm coming now...
Aahh.....
{i}At least it's done now.{/i}
{i}I'll get the USB drive and come home immediately.{/i}
Er?
Hehe.
What are you doing?
You agreed to help me satisfy my cock.
But look at it now.
Does it look satisfied?
But...
Delicious.
No, Mr Brie!
Just let it go, Ms Lee.
Ohhh...
{i}I can't back down now, just let him do what he wants and I can get the USB drive...{/i}
Are you ready, my dear?
Are you sure you'll give me the USB drive this time?
Of course, Ms Lee. Hehe.
Oohh...
You're so fucking tight, just like the last time!
Um... um...
Didn't you let anyone fuck you after me?
Um... um... no..
Then why don't you become my woman, girl?
No!... um... um...
Oh, you're so tight...
Huff... huff...
I can't hold it anymore...
Huff... please... take... huff... it out...
Ah... you're so tight...
Please....
Ah...
Um...
{i}Something is... releasing inside me...{/i}
{i}Is this what they call an orgasm?{/i}
You didn't pull it out?
You didn't realize that?
I guess you were busy with your cumming, right?
I... No, it's not like that!
Don't deny it, girl.
You had your orgasm.
That's why you didn't know I came inside you.
No...
She says no.
But deep down inside, she knows he's right about that.
After lunch, when you're on the way back to your desk...
Good afternoon.
Are you Mr [povname], sir?
Yes, I am.
How can I help you, officers?
We've got a report from Mr Brie that you attacked him last night.
His phone accidently recorded the incident because he forgot to turn the recording mode off.
Oh my gosh.
Accidently my ass.
Confused and worried, Suzie gets back to her desk, thinking...
{i}Because of me, now [povname] is in trouble.{/i}
{i}It's all my fault.{/i}
{i}How can I face his family if something happens to him?{/i}
{i}I can't let that happen.{/i}
{i}I think I know how to solve this...{/i}
Suzie decides to come to Mr Brie's place again that night.
Good evening, Ms Lee.
Good evening, Mr Brie.
Come in, please.
So, what can I do for you tonight, Ms Lee?
I think you know why I'm here.
Why?
I don't know.
Please drop your charge against [povname].
Why must I do that?
What can I do for you?
Become my woman.
You mean becoming your wife?
Silly girl.
Why should I marry anyone?
Just become my woman.
Hm...
Alright.
Now take off your clothes and lie down on the bed.
Suzie turns around to take off her clothes.
No, don't be like that.
Show me your face and your body.
Okay, wait for me.
Hahaha.
As Jim Brie stands above her...
Still don't wanna look at me, do you?
Now move your hands.
Let me see your tits.
Still keeping silent, Suzie moves her hands.
Hm...
So silent today.
Now, move your thighs.
Suzie just lies there, letting him do anything he wants.
Um...
She gives a soft moan when he starts to lick her pussy.
After seeing that her pussy starts to get wet, he stands up.
Now, give me your head.
Doesn't say anything, she turns away her head.
Deny?
Hm... Alright.
Waiting no more, Jim Brie enters Suzie.
Um...
Huff... huff...
How do you feel, Suzie?
Huff... huff...
Hm... still silent.
Huff... huff...
You will say kimochi in your language, right?
I... huff... am not... huff... Japanese...
Where are you from?
Um... Jiangsu...
What?
Is that a country?
Oh... I can't hold it anymore...
Um...
Oh...
So good... oh...
How do you feel?
Hm... You'll talk soon.
Oh!
{i}He's putting his hand just outside my pussy!{/i}
Looks like someone's dripping wet down there, eh?
No, that's... sweat!
Pussy's not dripping sweat, Suzie.
No, that's...
You're horny watching them, right?
No, I'm not!
Let's see then.
S... stop it! Woody!
Oh... oh...
Looks like your body's not lying, eh?
Mm... mm...
How do you feel, Suzie?
Mm... mm...
Do you usually touch yourself when you're alone?
No! Oh...
{i}What's this feeling?{/i}
{i}It's... so good...{/i}
{i}My pussy feels like it's melting just by the tip of his finger.{/i}
{i}Why is his finger so hot like this?...{/i}
Mm... mm...
Do you feel good, Suzie?
Don't... ask me... that...
It's embarrassed... mm...
{i}Look likes she's gonna come soon.{/i}
Oh... please... Woody...
I know what you need, Suzie.
Please... stop...
Trust me, I'll make you feel good.
Mm... mm...
{i}What's this feeling?{/i}
{i}Something's coming...{/i}
{i}No... I can't stand on my feet anymore...{/i}
Mm... mm...
{i}Something's coming...{/i}
{i}It's near...{/i}
{i}It's...{/i}
Ahh...
Oh my...
What an orgasm...
{i}I didn't even put my finger into her vagina yet.{/i}
{i}I was just rubbing outside of it.{/i}
{i}It seems that she doesn't have much experience in touching herself.{/i}
I... I'm tired, Woody.
I... want to go back.
{i}Huhm... I guess I should wait for another chance to eat her then. Haha.{/i}
Okay, let's go back, Suzie.
{i}I think that's all my fault.{/i}
{i}I knew he still loved me but I kept finding him when I was sad.{/i}
{i}Maybe I should let him make love with me just this time...{/i}
{i}His penis is preparing to enter me!{/i}
Alex, I'm not wet yet!
I don't care, you're mine!
Ouch, Alex!
{i}My vagina's so dry...{/i}
{i}It's hurt...{/i}
How do you feel, Emily?
I'm hurt, Alex...
You feel hurt with me, but feel good with [povname]?
Don't say that!
You're crazy, Alex...
Why not?
You're mine now but still thinking about him, Emily?
{i}Alex's crazy now.{/i}
{i}That's all my fault...{/i}
{i}Where's [povname] now?{/i}
{i}Does he know that I still love him?...{/i}
Oh... oh... you're so tight, Emily...
Mm... mm...
{i}What the hell are you doing, Emily?{/i}
{i}You love [povname] but you're letting his close friend fuck you?{/i}
Oh... oh...
{i}But... I'm starting to feel good.{/i}
{i}It's not hurt anymore.{/i}
Oh... oh...
I'm coming, Emily!
Outside, Alex!
No, you're mine!
Oh...
Ugh...
{i}He released inside me...{/i}
{i}Just when I started to feel good though.{/i}
{i}It's been two weeks since the last time already...{/i}
{i}I want more...{/i}
{i}But that's absolutely not a good decision to jump on him right now.{/i}
{i}I think I just let his penis stay inside of me for some more minutes.{/i}
{i}Oh my gosh!{/i}
{i}It's... hard again!{/i}
Oh... oh...
Oh... I love you, Emily...
Mm...mm...
Stop saying that, Alex... oh...
This isn't how to show love...
Mm... mm...
{i}He's speeding up, don't tell me he's coming again...{/i}
{i}No, I'm not satisfied yet...{/i}
Hey, Alex, let me on top of you...
You want to come, too?
No, it's just that... you're hurting me...
Oh... oh...
{i}Every time I want to come, I always climb on top of [povname].{/i}
{i}Somehow I could come easily this way.{/i}
Oh... fuck...
You're so good, Emily!
Oh... oh...
I'm coming, Emily!
{i}I'm gonna come too...{/i}
Oh... oh...
Ugh...
Mm... mm...
I want to love you every day, Emily...
{i}I rode another dick not [povname]'s and came...{/i}
{i}They don't know that I'm staying at Woody's place now.{/i}
{i}But he doesn't do anything to me for a whole week.{/i}
{i}I think I'll be fine.{/i}
Some hours later.
{i}Finally, I'm home.{/i}
Ugh...
{i}The door...{/i}
{i}Ah... My head is spinning around...{/i}
{i}I'm here finally...{/i}
Ugh...
Some minutes later.
Oh... shit...
{i}She smells like alcohol.{/i}
{i}She's drunk for sure.{/i}
Hmm...
I can't let you sleep like this, Suzie.
I'll help you change into your pajama.
Some minutes later.
Um...
{i}Where is this place?{/i}
{i}Why do I feel tickled down there?{/i}
Woody?
Oh...
{i}He's sucking my vagina...{/i}
{i}It's... dirty!{/i}
{i}But what is this feeling?{/i}
Um...
Woody... be patient...
We'll continue this on our wedding night...
Silent, Suzie.
Er?
You don't know what you're saying.
Let me show you what you really need.
I'm sure you'll thank me later.
Er?
Here we go.
Er?
Ah... I'm hurt... Woody!
Don't worry. It'll be over soon.
Ugh... so tight...
Ah...
Virgin is the best... Ugh...
Ah... gentle, please...
Ah...
Do you feel good, Suzie?
No... it's just... I'm so hurt... Ah...
Don't worry... you'll be fine...
You'll feel good next time...
Um...
You're so tight, Suzie... oh...
Mm... mm...
I love you, Suzie.
Finish it... please...
Oh... so tight!
Um...
A virgin pussy is so tight... oh...
Mm...
I can't hold it anymore...
Um...
Here I come, Suzie...
Ugh...
Oh... oh... receive my seeds, Suzie...
Ugh...
Um...
You're a woman now, my woman.
{i}I'm still hurt...{/i}
Why not?
Change her clothes!
Keep going!
Get closer.
Kiss her.
Do it.
Touch her crotch.
Don't touch her crotch.
Do more!

